#!/usr/bin/env php
<?php

declare(strict_types=1);

$response = file_get_contents("https://www.worldometers.info/coronavirus/");

if ($response === false) {
    echo '[*] Failed to retrieve the webpage content' . PHP_EOL;
    exit;
}

$pattern = '/<div class="maincounter-number".*?>\s*<span.*?>\s*([0-9,]+)\s*<\/span>\s*<\/div>/';

if (preg_match_all($pattern, $response, $matches)) {

    $data = [
        'total'     => $matches[1][0],
        'deaths'    => $matches[1][1],
        'recovered' => $matches[1][2]
    ];

    $template = "\n\n😷 Total cases: %s\n💀 Deaths: %s\n🙏 Recovered: %s \n\n";

    echo sprintf($template, $data['total'], $data['deaths'], $data['recovered']);
    exit;
}

echo "Failed to apply patterns!";
