version: '3.7'
services:
  app:
    build:
      args:
        user: ${USER}
        uid: 1000
      context: ./
      dockerfile: ./.devops/php/Dockerfile
    image: covidscrap-app
    container_name: covidscrap
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - covidscrap
networks:
  covidscrap:
    driver: bridge
